version: "3.4"

services:
  eventstoredb:
    image: eventstore/eventstore:latest
    environment:
      - EVENTSTORE_INSECURE=true # let eventstore run without ceritficate
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113" # map internal tcp port
      - "2113:2113" # map internal admin ui port
